name: Govulncheck Scan
on: [push, pull_request]

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: "1.25"
          go-package: "./..."
          output-format: "sarif"
          output-file: "govulncheck.sarif"
      # optional: upload SARIF to Code Scanning
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: govulncheck.sarif
